### ISSUE TITLE
bitwig clap produces strange electronic noise

### ISSUE THREAD

**Issue by RustoMCSpit** [sjoerdvankreel/firefly-synth#11]
i can provide audio if needed

**Comment by RustoMCSpit** [comment]
https://github.com/sjoerdvankreel/firefly-synth/assets/134429563/e5551d2d-310b-4054-84ba-ddf049bf0451

**Comment by RustoMCSpit** [comment]
no effects were used, it's not clipping

**Comment by sjoerdvankreel** [comment]
Sounds like buffer troubles to me. I bit like my USB audio device, or the way it sounds when run through a VM ;)

* What does another synth sound like ?
* What does another soundcard sound like ? (hoping you have more than 1)
* What if you play around with the host buffer size ? (btw, what are your settings ?)

**Comment by RustoMCSpit** [comment]
other synths sound fine
im using bluetooth? wdym by soundcard
my settings are the standard bitwig ones

**Comment by sjoerdvankreel** [comment]
<< other synths sound fine

So then it's definately firefly.
How about the V1.7.1 release ? I made some major changes in buffer handling after that one.

**Comment by RustoMCSpit** [comment]
so pre-1.7.1 or 1,7,1 exactly? what do you want me to test

**Comment by sjoerdvankreel** [comment]
1.7.1. i changed stuff in 1.7.2

**Comment by RustoMCSpit** [comment]
THIS FEELS LIKE A BLUETOOTH / BITWIG ISSUE, closing sorry for cap lock

**Comment by sjoerdvankreel** [comment]
Wait a sec. 
Didn't you just say other synths are fine?

**Comment by RustoMCSpit** [comment]
i ran firefly fine and then bitwig had an issue where i had to change audio output to my headphones (because it was unrecognised) and then it started going to shit, the issue seems to be bitwig
