### ISSUE TITLE
Clap shrinks too abnormal size

### ISSUE THREAD

**Issue by RustoMCSpit** [sjoerdvankreel/firefly-synth#4]
Linux Mint LTS Cinnamon
Bitwig Studio 5.1
[firefly_synth_fx_1.5.0_linux_clap.zip](https://github.com/sjoerdvankreel/firefly-synth-storage/blob/main/release/firefly_synth_fx_1.5.0_linux_clap.zip)

The synth shrinks too an abormal size upon opening it and it is seen as an effect rather than an instrument

**Comment by sjoerdvankreel** [comment]
Seems like you downloaded the FX version instead of the instrument version (https://github.com/sjoerdvankreel/firefly-synth-storage/blob/main/release/firefly_synth_1.5.0_linux_clap.zip).

**Comment by sjoerdvankreel** [comment]
Closing this as I'm guessing it is resolved. Feel free to re-open.
