### ISSUE TITLE
Latest zip files won't open on Windows 11

### ISSUE THREAD

**Issue by bmcclure** [sjoerdvankreel/firefly-synth#5]
I'm unsure if it's just my particular computer or if the Windows zip files are actually corrupt, but I've tried opening all of the Windows zip files for version 1.7.1 using multiple archive tools without success.

So far I have tried Windows Explorer's unzipping functionality as well as Directory Opus and they both think it's a corrupt file. Is a different third-party tool needed to open the files? What was used to create them?

Of note, I was able to open the zip file from at least a couple of previous versions without issue, it's only when I went to download 1.7.1 that I started having this problem.

Thanks!

**Comment by sjoerdvankreel** [comment]
I'm able to open them no problem, windows 10, using winrar https://www.win-rar.com/. Cannot test windows 11 unfortunately.
However I did switch zip tool somewhere around 2-3 weeks ago. Before, I manually zipped up everything using winrar. Now, I have it scripted using the windows built-in tar command. I guess that's the most likely culprit.

Here's some things to try:
- Can you unzip using winrar?
- Can you unzip using 7zip (works for me, too)?
- Can you unzip using windows' built in tar.exe command line tool?
- I uploaded a manually zipped version (again using winrar, "like before"), for 1.7.1 over here: https://github.com/sjoerdvankreel/firefly-synth-storage/raw/main/temp/firefly_synth_1.vst3.zip. Does that work for you?
- I switched zip tools starting from 1.6.0. Is that the release things stopped working? See https://github.com/sjoerdvankreel/firefly-synth-storage/tree/main/release.

Thanks for reporting btw. I had some other complaints already about issues using the windows archives, but nothing concrete that i could act on.

**Comment by sjoerdvankreel** [comment]
Fixed in 1.7.2. Can you confirm?

**Comment by sjoerdvankreel** [comment]
Assuming it's working, feel free to reopen.
