### ISSUE TITLE
synth cant display gui or it crashes

### ISSUE THREAD

**Issue by RustoMCSpit** [sjoerdvankreel/firefly-synth#9]
bitwig 5.1.9
linux mint cinnamon lts
clap plugin from release

**Comment by sjoerdvankreel** [comment]
Confirmed after upgrading bitwig 5.0.7 to 5.1.9, ubuntu 22.
Windows bitwig 5.1.9 is fine, unfortunately.
This may take a while.

**Comment by sjoerdvankreel** [comment]
Ok so here's what's going on:

* Tried firefly 1.7.5 release from my existing build => crash
* Tried firefly 1.7.6 debug from a clean build => ok
* Tried firefly 1.7.6 release from a clean build => ok
* Then tried firefly 1.7.5 release from a clean build => ok

I'm going to write this up to a bad build. Serves me right for not doing a full rebuild prior to release I guess.
If you want you can build from source for v1.7.6. In any case I'll upload new binaries somewhere this week.

**Comment by RustoMCSpit** [comment]
1.7.6 release? wheres that

**Comment by RustoMCSpit** [comment]
> It's just a git tag so you have to build from source. I'll try to upload new binaries later tonight.

awesome thanks

**Comment by sjoerdvankreel** [comment]
Ok so I added new release versions for v1.7.6 over here: https://github.com/sjoerdvankreel/firefly-synth-storage/tree/main/release.

Tried again with bitwig 5.1.9/firefly 1.7.6 CLAP. TBH, that setup crashed on me the first time I tried to load an existing demo song, so I'm still not fully convinced if there's nothing wrong. However after that, I'm able load the plugin including gui, create new tracks, load all existing demo material etc without problems. 

It would be helpful if you can maybe play around with 1.7.6 in the latest bitwig version ?

**Comment by RustoMCSpit** [comment]
doesnt work still, gui broken.

**Comment by RustoMCSpit** [comment]
crashes every time i load it in

**Comment by sjoerdvankreel** [comment]
Actually *maybe* it just hit me. It's a long shot, but bitwig fixed a plugin gui resizing bug in 5.1.8. They had the aspect ratio wrong, but firefly stores those values in a config file. I'm hoping, if you delete that config file, that might fix stuff.

It's in ~/.config/Sjoerd van Kreel/. You can safely delete anything in there, it's just gui settings. Or, if it's not there, see this: https://github.com/sjoerdvankreel/firefly-synth/issues/7.

Also, how about bitwig + firefly vst3? Or f.e. reaper + firefly clap? Are those good?

**Comment by RustoMCSpit** [comment]
i dont have reaper, i can check vst3

**Comment by sjoerdvankreel** [comment]
Beware that bitwig fix was specifically for CLAP though. 
I'd really like to know, if the clap might start working if you delete that config file?

**Comment by RustoMCSpit** [comment]
cant find the config file

**Comment by sjoerdvankreel** [comment]
thats for the FX version. there's another folder called 56AFFFF7565F48348C4359D5E6C856A4. but honestly, just delete anything under ~/.config/Sjoerd van Kreel

**Comment by RustoMCSpit** [comment]
theres nothing under .config with your name, i just installed the ,clap from releases and put it in my .clap folder

**Comment by sjoerdvankreel** [comment]
what's the parent folder of 4F18AFC06CA743C7AFEF578388E16CF3?

**Comment by RustoMCSpit** [comment]
> what's the parent folder of 4F18AFC06CA743C7AFEF578388E16CF3?

/var/tmp/Sjoerd van Kreel/Firefly Synth FX

**Comment by sjoerdvankreel** [comment]
Then drop anything under /var/tmp/Sjoerd van Kreel

**Comment by RustoMCSpit** [comment]
only thing there was the FireFly FX, deleted it

**Comment by RustoMCSpit** [comment]
the vst3 isnt even recognised (and is stored as a .so file?)

**Comment by RustoMCSpit** [comment]
i only store the clap btw, i do not store the presets or any other related files. is that causing it?

**Comment by sjoerdvankreel** [comment]
aha!

**Comment by sjoerdvankreel** [comment]
so glad you mentioned

**Comment by sjoerdvankreel** [comment]
yes you have to place the *entire* folder structure into the CLAP/VST3 folder

**Comment by RustoMCSpit** [comment]
one sec

**Comment by RustoMCSpit** [comment]
why is the release tag system the way it is, off-topic but why cant you just put it in releases

**Comment by sjoerdvankreel** [comment]
thats just me being lazy honestly. i'll look into that, someday ;)

**Comment by RustoMCSpit** [comment]
> yes you have to place the _entire_ folder structure into the CLAP/VST3 folder

this fixed it lmao

**Comment by RustoMCSpit** [comment]
> thats just me being lazy honestly. i'll look into that, someday ;)

look into studiorack too!!

**Comment by sjoerdvankreel** [comment]
<< this fixed it lmao
Pfew. I was getting kinda worried. You are not the first one to hit this problem.

Under "install" at the github main page it says this:'

"Install
Extract the zipped folder and copy/replace it (the entire folder, not just the .dll/.so/.dylib!) to your VST3/CLAP folder:"

Is that not clear enough ? Anything I can do to make that more self explanatory ?

**Comment by RustoMCSpit** [comment]
> Is that not clear enough ? Anything I can do to make that more self explanatory ?

add a .readme to the zip folder reading "you need to have the entire folder or it wont work"
